package work

const frontendScheduleFields = `s.*,c.tor_id,c.project_name,c.contract_no,l.location_name,l.address,l.latitude::text,l.longitude::text,u.first_name,u.last_name,((s.work_date+s.shift_start_time) AT TIME ZONE 'Asia/Bangkok') AS shift_start_at,((s.work_date+s.shift_start_time) AT TIME ZONE 'Asia/Bangkok')+interval '8 hours' AS shift_end_at`
const frontendScheduleJoins = ` FROM work_schedule s JOIN worker w ON w.worker_id=s.worker_id JOIN public."USER" u ON u.user_id=w.user_id JOIN tor_location_assignment a ON a.assignment_id=s.assignment_id JOIN contract_tor c ON c.tor_id=a.tor_id JOIN location l ON l.location_id=a.location_id `
const frontendSchedules = `SELECT ` + frontendScheduleFields + frontendScheduleJoins + `WHERE ($1::uuid IS NULL OR (w.user_id=$1 AND (s.work_date >= ($9::timestamptz AT TIME ZONE 'Asia/Bangkok')::date OR (s.shift_status='scheduled' AND ((s.work_date+s.shift_start_time) AT TIME ZONE 'Asia/Bangkok')+interval '8 hours' > $9::timestamptz)))) AND ($4='' OR s.shift_status::text=$4) AND ($5::uuid IS NULL OR s.assignment_id=$5) AND ($6::uuid IS NULL OR a.tor_id=$6) AND ($7='' OR s.work_date >= NULLIF($7,'')::date) AND ($8='' OR s.work_date <= NULLIF($8,'')::date) ORDER BY s.work_date,s.shift_start_time,s.schedule_id LIMIT $2 OFFSET $3`
const frontendLeaves = `SELECT lr.*,u.first_name,u.last_name,COALESCE((SELECT jsonb_agg(jsonb_build_object('schedule_id',s.schedule_id,'assignment_id',s.assignment_id,'shift_start_time',s.shift_start_time,'project_name',c.project_name,'location_name',l.location_name)) FROM worker w JOIN work_schedule s ON s.worker_id=w.worker_id JOIN tor_location_assignment a USING(assignment_id) JOIN contract_tor c USING(tor_id) JOIN location l USING(location_id) WHERE w.user_id=lr.user_id AND s.work_date=lr.leave_date),'[]'::jsonb) AS schedules FROM leave_request lr JOIN public."USER" u ON u.user_id=lr.user_id WHERE ($1::uuid IS NULL OR lr.user_id=$1) AND ($4='' OR lr.status::text=$4) AND ($7='' OR lr.leave_date>=NULLIF($7,'')::date) AND ($8='' OR lr.leave_date<=NULLIF($8,'')::date) AND (($5::uuid IS NULL AND $6::uuid IS NULL) OR EXISTS(SELECT 1 FROM worker w JOIN work_schedule s ON s.worker_id=w.worker_id JOIN tor_location_assignment a USING(assignment_id) WHERE w.user_id=lr.user_id AND s.work_date=lr.leave_date AND ($5::uuid IS NULL OR s.assignment_id=$5) AND ($6::uuid IS NULL OR a.tor_id=$6))) ORDER BY lr.created_at DESC,lr.request_id LIMIT $2 OFFSET $3`
const frontendAttendance = `SELECT att.*,s.assignment_id,c.tor_id,c.project_name,l.location_name,u.first_name,u.last_name FROM attendance att JOIN work_schedule s ON s.schedule_id=att.schedule_id JOIN worker w ON w.worker_id=att.worker_id JOIN public."USER" u ON u.user_id=w.user_id JOIN tor_location_assignment a ON a.assignment_id=s.assignment_id JOIN contract_tor c USING(tor_id) JOIN location l USING(location_id) WHERE ($1::uuid IS NULL OR w.user_id=$1) AND ($4='' OR att.status::text=$4) AND ($5::uuid IS NULL OR s.assignment_id=$5) AND ($6::uuid IS NULL OR a.tor_id=$6) AND ($7='' OR att.work_date>=NULLIF($7,'')::date) AND ($8='' OR att.work_date<=NULLIF($8,'')::date) ORDER BY att.work_date DESC,att.attendance_id LIMIT $2 OFFSET $3`
const frontendRequisitions = `SELECT r.*,a.tor_id,c.project_name,l.location_name,u.first_name,u.last_name FROM equipment_requisition r JOIN tor_location_assignment a USING(assignment_id) JOIN contract_tor c USING(tor_id) JOIN location l USING(location_id) JOIN public."USER" u ON u.user_id=r.requested_by WHERE ($1::uuid IS NULL OR r.requested_by=$1) AND ($4='' OR r.status::text=$4) AND ($5::uuid IS NULL OR r.assignment_id=$5) AND ($6::uuid IS NULL OR a.tor_id=$6) AND ($7='' OR (r.created_at AT TIME ZONE 'Asia/Bangkok')::date>=NULLIF($7,'')::date) AND ($8='' OR (r.created_at AT TIME ZONE 'Asia/Bangkok')::date<=NULLIF($8,'')::date) AND ($9='' OR r.requisition_type::text=$9) ORDER BY r.created_at DESC,r.requisition_id LIMIT $2 OFFSET $3`
const frontendCandidatePredicate = ` FROM public."USER" u WHERE u.role='worker' AND u.is_active AND ($2::uuid IS NULL OR u.user_id<>$2) AND EXISTS(SELECT 1 FROM worker w WHERE w.user_id=u.user_id AND w.is_available) AND NOT EXISTS(SELECT 1 FROM worker w JOIN work_schedule s ON s.worker_id=w.worker_id WHERE w.user_id=u.user_id AND s.work_date=$1::date) AND NOT EXISTS(SELECT 1 FROM leave_request lr WHERE lr.user_id=u.user_id AND lr.leave_date=$1::date AND lr.status='approved') AND NOT EXISTS(SELECT 1 FROM payroll p WHERE p.user_id=u.user_id AND $1::date BETWEEN p.period_start AND p.period_end)`
const frontendCandidateUsers = `SELECT u.user_id::text` + frontendCandidatePredicate + ` ORDER BY u.user_id`
const frontendCandidates = `SELECT u.user_id,w.worker_id,u.first_name,u.last_name,w.is_available FROM worker w JOIN public."USER" u ON u.user_id=w.user_id WHERE u.user_id IN (SELECT u.user_id` + frontendCandidatePredicate + `) ORDER BY u.first_name,u.last_name,u.user_id LIMIT $3 OFFSET $4`
const frontendLeaveDetail = `SELECT lr.*,u.first_name,u.last_name,w.worker_id,s.schedule_id,s.assignment_id,s.shift_start_time,c.tor_id,c.project_name,l.location_name FROM leave_request lr JOIN public."USER" u ON u.user_id=lr.user_id JOIN worker w ON w.user_id=u.user_id JOIN work_schedule s ON s.worker_id=w.worker_id AND s.work_date=lr.leave_date JOIN tor_location_assignment a USING(assignment_id) JOIN contract_tor c USING(tor_id) JOIN location l USING(location_id) WHERE lr.request_id=$1`
const frontendAssignments = `SELECT a.*,c.contract_no,c.project_name,c.status AS contract_status,c.start_date,c.end_date,l.location_name,l.latitude::text,l.longitude::text,(c.status='active' AND ($2::timestamptz AT TIME ZONE 'Asia/Bangkok')::date BETWEEN c.start_date AND c.end_date) AS can_schedule FROM tor_location_assignment a JOIN contract_tor c USING(tor_id) JOIN location l USING(location_id) WHERE ($1::uuid IS NULL OR a.tor_id=$1) ORDER BY c.project_name,l.location_name,a.assignment_id LIMIT $3 OFFSET $4`

const frontendDashboard = `SELECT (SELECT count(*) FROM contract_tor WHERE status IN ('registered','active')) AS open_contracts,(SELECT count(*) FROM leave_request WHERE status='pending') AS pending_leave,(SELECT count(*) FROM equipment_requisition WHERE status NOT IN ('completed','rejected')) AS open_requisitions,COALESCE((SELECT jsonb_agg(to_jsonb(c)) FROM (SELECT tor_id,project_name,status,start_date,end_date,CASE WHEN status IN ('complete','cancelled') OR end_date<($1::timestamptz AT TIME ZONE 'Asia/Bangkok')::date THEN 'ended' WHEN status='active' AND start_date<=($1::timestamptz AT TIME ZONE 'Asia/Bangkok')::date THEN 'active' ELSE 'registered' END AS workflow_status,(status='active' AND ($1::timestamptz AT TIME ZONE 'Asia/Bangkok')::date BETWEEN start_date AND end_date) AS can_operate FROM contract_tor ORDER BY created_at DESC,tor_id LIMIT 100) c),'[]'::jsonb) AS contracts`
